first_django_project/ads/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name = 'ads'
urlpatterns = [
    path('', views.AdListView.as_view(), name='all'),
    path('ad/<int:pk>', views.AdDetailView.as_view(), name='ad_detail'),
    path('ad_picture/<int:pk>', views.stream_file, name='ad_picture'),
    path('ad/create', views.AdCreateView.as_view(
        success_url=reverse_lazy('ads:all')),
        name='ad_create'),
    path('ad/<int:pk>/update', views.AdUpdateView.as_view(
        success_url=reverse_lazy('ads:all')),
        name='ad_update'),
    path('ad/<int:pk>/delete', views.AdDeleteView.as_view(
        success_url=reverse_lazy('ads:all')),
        name='ad_delete'),
    path(
        'ad/<int:pk>/comment',
        views.CommentCreateView.as_view(),
        name='ad_comment_create'
    ),
    path(
        'comment/<int:pk>/delete',
        views.CommentDeleteView.as_view(success_url=reverse_lazy('ads:all')),
        name='ad_comment_delete'
    ),
    path(
        'ad/<int:pk>/favorite',
        views.AddFavoriteView.as_view(),
        name='ad_favorite'
    ),
    path(
        'ad/<int:pk>/unfavorite',
        views.DeleteFavoriteView.as_view(),
        name='ad_unfavorite'
    )
]

# We use reverse_lazy in urls.py to delay looking up the view
# until all the paths are defined

first_django_project/autos/urls.py
from django.urls import path
from . import views

app_name = 'autos'
urlpatterns = [
    # path('', views.main_page, name='main_page'),
    # path('manufacturers/', views.manufacturers_page, name='manufacturers_page'),
    # path('add_manufacturer/', views.manufacturer_add_form, name='add_manufacturer'),
    # path('<int:pk>/edit_manufacturer/', views.manufacturer_edit_form, name='edit_manufacturer'),
    # path('<int:pk>/delete_manufacturer/', views.manufacturer_delete_form, name='delete_manufacturer'),
    # path('add_auto/', views.auto_add_form, name='add_auto'),
    # path('<int:pk>/edit_auto/', views.auto_edit_form, name='edit_auto'),
    # path('<int:pk>/delete_auto/', views.auto_delete, name='delete_auto'),
    path('', views.MainPage.as_view(), name='main_page'),
    path('makers/', views.MakersPage.as_view(), name='makers_page'),
    path('add_maker/', views.CreateMaker.as_view(), name='add_maker'),
    path('edit_maker/<int:pk>/', views.UpdateMaker.as_view(), name='edit_maker'),
    path('delete_maker/<int:pk>/', views.DeleteMaker.as_view(), name='delete_maker'),
    path('add_auto/', views.CreateAuto.as_view(), name='add_auto'),
    path('edit_auto/<int:pk>/', views.UpdateAuto.as_view(), name='edit_auto'),
    path('delete_auto/<int:pk>/', views.DeleteAuto.as_view(), name='delete_auto'),
]

first_django_project/cats/urls.py
from django.urls import path
from . import views

app_name = 'cats'
urlpatterns = [
    path('', views.CatsPage.as_view(), name='cats_page'),
    path('breeds/', views.BreedsPage.as_view(), name='breeds_page'),
    path('create/breed/', views.CreateBreed.as_view(), name='create_breed'),
    path('update/breed/<int:pk>/', views.UpdateBreed.as_view(), name='update_breed'),
    path('delete/breed/<int:pk>/', views.DeleteBreed.as_view(), name='delete_breed'),
    path('create/cat/', views.CreateCat.as_view(), name='create_cat'),
    path('update/cat/<int:pk>/', views.UpdateCat.as_view(), name='update_cat'),
    path('delete/cat/<int:pk>', views.DeleteCat.as_view(), name='delete_cat'),
]

first_django_project/home/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.HomeView.as_view()),
]

first_django_project/mysite/urls.py
import os
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.conf.urls import url
from django.views.static import serve
from django.views.generic import TemplateView

# Up two folders to serve "site" content
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE_ROOT = os.path.join(BASE_DIR, 'site')

urlpatterns = [
    path('', TemplateView.as_view(template_name='home/main.html')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('autos/', include('autos.urls')),
    path('cats/', include('cats.urls')),
    path('ads/', include('ads.urls')),
    path('hello/', include('hello.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    re_path(r'^oauth/', include('social_django.urls', namespace='social')),
]

# Serve the static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    re_path(r'^site/(?P<path>.*)$', serve, {
        'document_root': os.path.join(BASE_DIR, 'site'),
        'show_indexes': True
        },
        name='site_path'
        ),
]

# Serve the favicon - Keep for later
urlpatterns += [
    path('favicon.ico', serve, {
            'path': 'favicon.ico',
            'document_root': os.path.join(BASE_DIR, 'home/static'),
        }
    ),
]

# Switch to social login if it is configured - Keep for later
try:
    from . import github_settings
    social_login = 'registration/login_social.html'
    urlpatterns.insert(0, path(
        'accounts/login/',
        auth_views.LoginView.as_view(template_name=social_login)
        )
    )
    print('Using', social_login, 'as the login template')
except:
    print('Using registration/login.html as the login template')

# References

# https://docs.djangoproject.com/en/3.0/ref/urls/#include

first_django_project/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    # ex: /polls/
    path('', views.IndexView.as_view(), name='index'),
    # ex: /polls/5/
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # ex: /polls/5/results/
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
    # ex: dj4e task
    path('owner', views.owner, name='owner'),
]

first_django_project/home/views.py
from django.shortcuts import render
from django.views import View
from django.conf import settings

# Create your views here.

# This is a little complex because we need to detect when we are
# running in various configurations


class HomeView(View):
    def get(self, request):
        print(request.get_host())
        host = request.get_host()
        islocal = host.find('localhost') >= 0 or host.find('127.0.0.1') >= 0
        context = {
            'installed': settings.INSTALLED_APPS,
            'islocal': islocal
        }
        return render(request, 'home/main.html', context)

first_django_project/home/templates/home/base_bootstrap.html
<!DOCTYPE html>
<html>
<head>
<!-- Edit dj4e-samples/settings.py and add APP_NAME = 'DJ4E Samples' or similar -->
<title>{% block title %}{{ settings.APP_NAME }}{% endblock %}</title>

<!-- Replace this value (42-42) with the one provided by the autograder -->
<meta name="dj4e" content="1a2d4440e811095c06073e6671536a68">

<meta name="dj4e-code" content="42166288812330">

<link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css"
    crossorigin="anonymous">

<link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap-theme.min.css"
    crossorigin="anonymous">

<link rel="stylesheet"
    href="https://code.jquery.com/ui/1.12.1/themes/ui-lightness/jquery-ui.css"
     crossorigin="anonymous">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"
    crossorigin="anonymous"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"
    crossorigin="anonymous"></script>

<script
  src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"
  crossorigin="anonymous"></script>

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/v4-shims.css">

<meta name="dj4e-version" content="2022-09-01">

{% block head %} {% endblock %}

</head>
<body>
<div class="container">
{% block navbar %} {% endblock %}
{% block welcome %} {% endblock %}
{% block messages %}
    {% if messages %}
    {% for msg in messages %}
        <div class="alert alert-{{msg.level_tag}}" role="alert">
        {{msg.message}}
        </div>
    {% endfor %}
    {% endif %}
{% endblock %}
{% block content %}
{% endblock %}
</div>
{% block footer %} {% endblock %}
</body>
</html>

first_django_project/home/templates/home/base_menu.html
{% extends "home/base_bootstrap.html" %}
{% block navbar %}
{% load app_tags %}
<nav class="navbar navbar-default navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
        <a class="navbar-brand" href="/">{{ settings.APP_NAME }}</a>
    </div>
    <!-- https://stackoverflow.com/questions/22047251/django-dynamically-get-view-url-and-check-if-its-the-current-page -->
    <ul class="nav navbar-nav">
      {% url 'ads' as ads %}
      <li {% if request.get_full_path == ads %}class="active"{% endif %}>
          <a href="{% url 'ads:all' %}">Ads</a></li>
      {% url 'cats' as cats %}
      <li {% if request.get_full_path == cats %}class="active"{% endif %}>
          <a href="{% url 'cats:cats_page' %}">Cats</a></li>
      {% url 'autos' as autos %}
      <li {% if request.get_full_path == cats %}class="active"{% endif %}>
          <a href="{% url 'autos:main_page' %}">Autos</a></li>
      {% url 'polls' as polls %}
      <li {% if request.get_full_path == polls %}class="active"{% endif %}>
          <a href="{% url 'polls:index' %}">Polls</a></li>
        
    </ul>
    <ul class="nav navbar-nav navbar-right">
        {% if user.is_authenticated %}
        <li>
        <a href="{% url 'ads:ad_create' %}">Create Ad</a>
        </li>
        <li class="dropdown">
            <a href="#" data-toggle="dropdown" class="dropdown-toggle">
                <img style="width: 25px;" src="{{ user|gravatar:60 }}"/><b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
                <li><a href="{% url 'logout' %}?next={% url 'ads:all' %}">Logout</a></li>
            </ul>
        </li>
        {% else %}
        <li>
        <a href="{% url 'login' %}?next={% url 'ads:all' %}">Login</a>
        </li>
        {% endif %}
    </ul>
  </div>
</nav>
{% endblock %}

first_django_project/home/templates/home/main.html
<ul>
    <li><p><a href="/polls">A Polls Application</a></p></li>
    <li><p><a href="/autos">Autos CRUD</a></p></li>
    <li><p><a href="/cats">Cats CRUD</a></p></li>
    <li><p><a href="/ads">Ads CRUD</a></p></li>
    <li><p><a href="/hello">Test the session</a></p></li>
    <li><p><a href="/admin">Админка</a></p></li>
    </ul>
    