first_django_project/ads/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name = 'ads'
urlpatterns = [
    path('', views.AdListView.as_view(), name='all'),
    path('ad/<int:pk>', views.AdDetailView.as_view(), name='ad_detail'),
    path('ad_picture/<int:pk>', views.stream_file, name='ad_picture'),
    path('ad/create', views.AdCreateView.as_view(
        success_url=reverse_lazy('ads:all')),
        name='ad_create'),
    path('ad/<int:pk>/update', views.AdUpdateView.as_view(
        success_url=reverse_lazy('ads:all')),
        name='ad_update'),
    path('ad/<int:pk>/delete', views.AdDeleteView.as_view(
        success_url=reverse_lazy('ads:all')),
        name='ad_delete'),
    path(
        'ad/<int:pk>/comment',
        views.CommentCreateView.as_view(),
        name='ad_comment_create'
    ),
    path(
        'comment/<int:pk>/delete',
        views.CommentDeleteView.as_view(success_url=reverse_lazy('ads:all')),
        name='ad_comment_delete'
    ),
    path(
        'ad/<int:pk>/favorite',
        views.AddFavoriteView.as_view(),
        name='ad_favorite'
    ),
    path(
        'ad/<int:pk>/unfavorite',
        views.DeleteFavoriteView.as_view(),
        name='ad_unfavorite'
    )
]

# We use reverse_lazy in urls.py to delay looking up the view
# until all the paths are defined

first_django_project/cats/urls.py
from django.urls import path
from . import views

app_name = 'cats'
urlpatterns = [
    path('', views.CatsPage.as_view(), name='cats_page'),
    path('breeds/', views.BreedsPage.as_view(), name='breeds_page'),
    path('create/breed/', views.CreateBreed.as_view(), name='create_breed'),
    path('update/breed/<int:pk>/', views.UpdateBreed.as_view(), name='update_breed'),
    path('delete/breed/<int:pk>/', views.DeleteBreed.as_view(), name='delete_breed'),
    path('create/cat/', views.CreateCat.as_view(), name='create_cat'),
    path('update/cat/<int:pk>/', views.UpdateCat.as_view(), name='update_cat'),
    path('delete/cat/<int:pk>', views.DeleteCat.as_view(), name='delete_cat'),
]

first_django_project/mysite/urls.py
import os
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.conf.urls import url
from django.views.static import serve
from django.views.generic import TemplateView

# Up two folders to serve "site" content
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE_ROOT = os.path.join(BASE_DIR, 'site')

urlpatterns = [
    path('', TemplateView.as_view(template_name='home/main.html')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('autos/', include('autos.urls')),
    path('cats/', include('cats.urls')),
    path('ads/', include('ads.urls')),
    path('hello/', include('hello.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    re_path(r'^oauth/', include('social_django.urls', namespace='social')),
]

# Serve the static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    re_path(r'^site/(?P<path>.*)$', serve, {
        'document_root': os.path.join(BASE_DIR, 'site'),
        'show_indexes': True
        },
        name='site_path'
        ),
]

# Serve the favicon - Keep for later
urlpatterns += [
    path('favicon.ico', serve, {
            'path': 'favicon.ico',
            'document_root': os.path.join(BASE_DIR, 'home/static'),
        }
    ),
]

# Switch to social login if it is configured - Keep for later
try:
    from . import github_settings
    social_login = 'registration/login_social.html'
    urlpatterns.insert(0, path(
        'accounts/login/',
        auth_views.LoginView.as_view(template_name=social_login)
        )
    )
    print('Using', social_login, 'as the login template')
except:
    print('Using registration/login.html as the login template')

# References

# https://docs.djangoproject.com/en/3.0/ref/urls/#include

first_django_project/cats/models.py
from django.db import models
from django.core.validators import MinLengthValidator

class Breed(models.Model):
    name = models.CharField(
        max_length=30,
        validators=[MinLengthValidator(2, "Название породы должно быть минимум из двух символов")]
    )

    def __str__(self):
        return self.name


class Cat(models.Model):
    nickname = models.CharField(
        max_length=20,
        validators=[MinLengthValidator(2, "Имя кошарика должно быть минимум из двух символов")]
    )
    weight = models.PositiveIntegerField()
    foods = models.CharField(max_length=300)
    breed = models.ForeignKey('Breed', on_delete=models.CASCADE, null=False)

    def __str__(self):
        return self.nickname

first_django_project/cats/forms.py
from django.forms import ModelForm
from .models import Cat, Breed

class BreedForm(ModelForm):
    class Meta:
        model = Breed
        fields = '__all__'

class CatForm(ModelForm):
    class Meta:
        model = Cat
        fields = '__all__'

first_django_project/cats/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Cat, Breed
from .forms import CatForm, BreedForm


class CatsPage(LoginRequiredMixin, View):
    def get(self, request):
        cats = Cat.objects.all()
        breeds_counter = Breed.objects.all().count()
        context = {
            'cats': cats,
            'breeds_counter': breeds_counter
        }
        return render(request, 'cats/cats_page.html', context)

class BreedsPage(LoginRequiredMixin, View):
    def get(self, request):
        breeds = Breed.objects.all()
        context = {'breeds': breeds}
        return render(request, 'cats/breeds_page.html', context)

class CreateBreed(LoginRequiredMixin, View):
    template = 'cats/breed_form.html'
    success_url = reverse_lazy('cats:cats_page')

    def get(self, request):
        form = BreedForm()
        context = {
            'form': form,
            'header': 'Добавление породы',
            'button': 'Добавить',
            }
        return render(request, self.template, context)

    def post(self, request):
        form = BreedForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(self.success_url)
        else:
            context = {
                'form': form,
                'header': 'Добавление породы',
                'button': 'Добавить',
            }
            return render (request, self.template, context)

class UpdateBreed(LoginRequiredMixin, View):
    model = Breed
    template = 'cats/breed_form.html'
    success_url = reverse_lazy('cats:cats_page')

    def get(self, request, pk):
        breed = get_object_or_404(self.model, pk=pk)
        form = BreedForm(instance=breed)
        context = {
            'form': form,
            'header': 'Обновление породы',
            'button': 'Обновить',
            }
        return render(request, self.template, context)

    def post(self, request, pk):
        breed = get_object_or_404(self.model, pk=pk)
        form = BreedForm(request.POST, instance=breed)
        if form.is_valid():
            form.save()
            return redirect(self.success_url)
        else:
            context = {
                'form': form,
                'header': 'Обновление породы',
                'button': 'Обновить',
            }
            return render(request, self.template, context)

class DeleteBreed(LoginRequiredMixin, View):
    model = Breed
    template = 'cats/breed_delete.html'
    success_url = reverse_lazy('cats:cats_page')

    def get(self, request, pk):
        breed = get_object_or_404(self.model, pk=pk)
        context = {'breed': breed}
        return render(request, self.template, context)

    def post(self, request, pk):
        breed = get_object_or_404(self.model, pk=pk)
        breed.delete()
        return redirect(self.success_url)

class CreateCat(LoginRequiredMixin, View):
    template = 'cats/cat_form.html'
    success_url = reverse_lazy('cats:cats_page')

    def get(self, request):
        form = CatForm
        context = {
            'form': form,
            'header': 'Добавление кошарика',
            'button': 'Добавить',
        }
        return render(request, self.template, context)
    
    def post(self, request):
        form = CatForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(self.success_url)
        else:
            context = {
                'form': form,
                'header': 'Добавление кошарика',
                'button': 'Добавить',
            }
            return render(request, self.template, context)

class UpdateCat(LoginRequiredMixin, View):
    model = Cat
    template = 'cats/cat_form.html'
    success_url = reverse_lazy('cats:cats_page')

    def get(self, request, pk):
        cat = get_object_or_404(self.model, pk=pk)
        form = CatForm(instance=cat)
        context = {
            'form': form,
            'header': 'Обновление кошарика',
            'button': 'Обновить',
        }
        return render(request, self.template, context)

    def post(self, request, pk):
        cat = get_object_or_404(self.model, pk=pk)
        form = CatForm(request.POST, instance=cat)
        if form.is_valid():
            form.save()
            return redirect(self.success_url)
        else:
            context = {
                'form': form,
                'header': 'Обновление кошарика',
                'button': 'Обновить',
            }
            return render(request, self.template, context)

class DeleteCat(LoginRequiredMixin, View):
    model = Cat
    template = 'cats/cat_delete.html'
    success_url = reverse_lazy('cats:cats_page')

    def get(self, request, pk):
        cat = get_object_or_404(self.model, pk=pk)
        context = {'cat': cat}
        return render(request, self.template, context)

    def post(self, request, pk):
        cat = get_object_or_404(self.model, pk=pk)
        cat.delete()
        return redirect(self.success_url)

first_django_project/cats/templates/cats/breed_delete.html
{% extends 'home/base_menu.html' %}
{% block content %}
<h1>Удаление породы</h1>
<p>Удалить породу "{{breed}}"?</p>
<form action="" method="post">
    {% csrf_token %}
    <p>
    <input type="submit" value="Удалить">
    <input type="submit" onclick="window.location='{% url 'cats:cats_page' %}'; return false;" value="Отмена">
    </p>
</form>
{% endblock %}

first_django_project/cats/templates/cats/breed_form.html
{% extends 'home/base_menu.html' %}
{% block content %}
<h1>{{ header }}</h1>
<form action="" method="post">
    {% csrf_token %}
    <p>{{ form.as_table }}</p>
    <p>
    <input type="submit" value="{{ button }}">
    <input type="submit" onclick="window.location='{% url 'cats:cats_page' %}'; return false;" value="Отмена">
    </p>
</form>
{% endblock %}

first_django_project/cats/templates/cats/breeds_page.html
{% extends 'home/base_menu.html' %}
{% block content %}
<h1>Породы</h1>
{% if breeds %}
    <p>{% for record in breeds %}
        <li>{{ record.name }} (<a href="{% url 'cats:update_breed' record.id %}">Обновить</a> | <a href="{% url 'cats:delete_breed' record.id %}">Удалить</a>)</li>
    {% endfor %}</p>
{% else %}
    <p>В базе нет ни одной породы</p>
{% endif %}
<p><a href="{% url 'cats:create_breed' %}">Добавить породу</a></p>
<p><a href="{% url 'cats:cats_page' %}">Назад к кошарикам</a></p>
{% endblock %}

first_django_project/cats/templates/cats/cat_delete.html
{% extends 'home/base_menu.html' %}
{% block content %}
<h1>Удаление кошарика</h1>
<p>Удалить из базы котейку "{{ cat }}"?</p>
    <form action="" method="post">
        {% csrf_token %}
        <p>
            <input type="submit" value="Удалить">
            <input type="submit" onclick="window.location='{% url 'cats:cats_page' %}'; return false;" value="Отмена">
        </p>
    </form>
{% endblock %}

first_django_project/cats/templates/cats/cat_form.html
{% extends 'home/base_menu.html' %}
{% block content %}
<h1>{{ header }}</h1>
<form action="" method="post">
    {% csrf_token %}
    <table>{{ form.as_table }}</table>
    <p>
        <input type="submit" value="{{ button }}">
        <input type="submit" onclick="window.location='{% url 'cats:cats_page' %}'; return false;" value="Отмена">
    </p>
</form>
{% endblock %}

first_django_project/cats/templates/cats/cats_page.html
{% extends 'home/base_menu.html' %}
{% block content %}
<h1>Кошарики</h1>
{% if cats %}
    <ul>
        {% for record in cats %}
            <li>{{ record.nickname }} ({{ record.breed }}) (<a href="{% url 'cats:update_cat' record.id %}">Обновить</a> | <a href="{% url 'cats:delete_cat' record.id %}">Удалить</a>)</li>
        {% endfor %}
    </ul>
{% else %}
    <p>В базе нет ни одного кошарика :(</p>
    <p>Перед тем как добавить кошарика, должна быть создана хотя бы одна порода</p>
{% endif %}
<p><a href="{% url 'cats:create_cat' %}">Добавить кисулю</a></p>
<p><a href="{% url 'cats:breeds_page' %}">Посмохтреть породы ({{breeds_counter}})</a> | <a href="{% url 'cats:create_breed' %}">Добавить породу</a></p>
{% endblock %}