first_django_project/ads/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name = 'ads'
urlpatterns = [
    path('', views.AdListView.as_view(), name='all'),
    path('ad/<int:pk>', views.AdDetailView.as_view(), name='ad_detail'),
    path('ad_picture/<int:pk>', views.stream_file, name='ad_picture'),
    path('ad/create', views.AdCreateView.as_view(
        success_url=reverse_lazy('ads:all')),
        name='ad_create'),
    path('ad/<int:pk>/update', views.AdUpdateView.as_view(
        success_url=reverse_lazy('ads:all')),
        name='ad_update'),
    path('ad/<int:pk>/delete', views.AdDeleteView.as_view(
        success_url=reverse_lazy('ads:all')),
        name='ad_delete'),
    path(
        'ad/<int:pk>/comment',
        views.CommentCreateView.as_view(),
        name='ad_comment_create'
    ),
    path(
        'comment/<int:pk>/delete',
        views.CommentDeleteView.as_view(success_url=reverse_lazy('ads:all')),
        name='ad_comment_delete'
    ),
    path(
        'ad/<int:pk>/favorite',
        views.AddFavoriteView.as_view(),
        name='ad_favorite'
    ),
    path(
        'ad/<int:pk>/unfavorite',
        views.DeleteFavoriteView.as_view(),
        name='ad_unfavorite'
    )
]

# We use reverse_lazy in urls.py to delay looking up the view
# until all the paths are defined

first_django_project/autos/urls.py
from django.urls import path
from . import views

app_name = 'autos'
urlpatterns = [
    # path('', views.main_page, name='main_page'),
    # path('manufacturers/', views.manufacturers_page, name='manufacturers_page'),
    # path('add_manufacturer/', views.manufacturer_add_form, name='add_manufacturer'),
    # path('<int:pk>/edit_manufacturer/', views.manufacturer_edit_form, name='edit_manufacturer'),
    # path('<int:pk>/delete_manufacturer/', views.manufacturer_delete_form, name='delete_manufacturer'),
    # path('add_auto/', views.auto_add_form, name='add_auto'),
    # path('<int:pk>/edit_auto/', views.auto_edit_form, name='edit_auto'),
    # path('<int:pk>/delete_auto/', views.auto_delete, name='delete_auto'),
    path('', views.MainPage.as_view(), name='main_page'),
    path('makers/', views.MakersPage.as_view(), name='makers_page'),
    path('add_maker/', views.CreateMaker.as_view(), name='add_maker'),
    path('edit_maker/<int:pk>/', views.UpdateMaker.as_view(), name='edit_maker'),
    path('delete_maker/<int:pk>/', views.DeleteMaker.as_view(), name='delete_maker'),
    path('add_auto/', views.CreateAuto.as_view(), name='add_auto'),
    path('edit_auto/<int:pk>/', views.UpdateAuto.as_view(), name='edit_auto'),
    path('delete_auto/<int:pk>/', views.DeleteAuto.as_view(), name='delete_auto'),
]

first_django_project/mysite/urls.py
import os
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.conf.urls import url
from django.views.static import serve
from django.views.generic import TemplateView

# Up two folders to serve "site" content
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE_ROOT = os.path.join(BASE_DIR, 'site')

urlpatterns = [
    path('', TemplateView.as_view(template_name='home/main.html')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('autos/', include('autos.urls')),
    path('cats/', include('cats.urls')),
    path('ads/', include('ads.urls')),
    path('hello/', include('hello.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    re_path(r'^oauth/', include('social_django.urls', namespace='social')),
]

# Serve the static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    re_path(r'^site/(?P<path>.*)$', serve, {
        'document_root': os.path.join(BASE_DIR, 'site'),
        'show_indexes': True
        },
        name='site_path'
        ),
]

# Serve the favicon - Keep for later
urlpatterns += [
    path('favicon.ico', serve, {
            'path': 'favicon.ico',
            'document_root': os.path.join(BASE_DIR, 'home/static'),
        }
    ),
]

# Switch to social login if it is configured - Keep for later
try:
    from . import github_settings
    social_login = 'registration/login_social.html'
    urlpatterns.insert(0, path(
        'accounts/login/',
        auth_views.LoginView.as_view(template_name=social_login)
        )
    )
    print('Using', social_login, 'as the login template')
except:
    print('Using registration/login.html as the login template')

# References

# https://docs.djangoproject.com/en/3.0/ref/urls/#include

first_django_project/autos/models.py
from django.db import models


class Manufacturer(models.Model):
    name = models.CharField(("Maker"), max_length=50)

    def __str__(self):
        return self.name


class Auto(models.Model):
    nickname = models.CharField(("Nickname"), max_length=20)
    mileage = models.IntegerField(("Milleage"), default=0)
    comments = models.CharField(("Comments"), max_length=50)
    make = models.ForeignKey(Manufacturer, on_delete=models.CASCADE, null=False)

    def __str__(self):
        return self.nickname

first_django_project/autos/forms.py
from django.forms import ModelForm
from autos.models import Auto, Manufacturer

class MakerForm(ModelForm):
    class Meta:
        model = Manufacturer
        fields = '__all__'

class AutoForm(ModelForm):
    class Meta:
        model = Auto
        fields = '__all__'

first_django_project/autos/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin  # для авторизации
from django.views import View
# from django.views.generic.edit import CreateView, UpdateView, DeleteView  # не использую здесь

from .models import Manufacturer, Auto
from .forms import MakerForm, AutoForm

"""
def main_page(request):
    autos = Auto.objects.all()
    manufacturers = Manufacturer.objects.all()
    context = {
        'autos': autos,
        'manufacturers': manufacturers,
        'counter': len(manufacturers),
        'edit': False,
    }
    return render(request, 'autos/main_page.html', context)
"""

class MainPage(LoginRequiredMixin, View):
    def get(self, request):
        autos = Auto.objects.all()
        manufacturers = Manufacturer.objects.all()
        context = {
            'autos': autos,
            'counter': len(manufacturers),
        }
        return render(request, 'autos/main_page.html', context)


"""
def manufacturers_page(request):
    manufacturers = Manufacturer.objects.all()
    context = {'manufacturers': manufacturers}
    return render(request, 'autos/manufacturers_page.html', context)
"""


class MakersPage(LoginRequiredMixin, View):
    def get(self, request):
        makers = Manufacturer.objects.all()
        context = {'makers': makers}
        return render(request, 'autos/manufacturers_page.html', context)


"""
def manufacturer_add_form(request):
    if request.method == 'POST':  # нажатие на кнопку submit
        if request.POST.get('manufacturer'):  # проверка содержимого в поле "Производитель" html-формы; параметр 'manufacturer' - значение параметра 'name' соответствующего поля ввода формы
            post = Manufacturer()  # переменная для работы с таблицей 'Manufacturer' (models.py)
            post.name = request.POST.get('manufacturer')  # присваиваем переменной таблицы значение, полученное из html-формы
            post.save()  # сохраняем запись в таблице
            return redirect(reverse_lazy('autos:main_page'))
        elif request.POST.get('cancel'):
            return redirect(reverse_lazy('autos:main_page'))
    else:
        return render(request, 'autos/add_manufacturer.html')
"""


class CreateMaker(LoginRequiredMixin, View):
    # переменные класса
    template = 'autos/add_or_edit_manufacturer.html'
    success_url = reverse_lazy('autos:main_page')

    def get(self, request):  # открытие страницы с пустой формой
        form = MakerForm()
        context = {'form': form}
        return render(request, self.template, context)

    def post(self, request):  # отправка на сервер заполненной формы
        form = MakerForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(self.success_url)
        else:
            context = {'form': form}
            return render(request, self.template, context)


"""
def manufacturer_edit_form(request, pk):
    manufacturer = Manufacturer.objects.filter(pk=pk).values()
    dict_from_quiery_set = manufacturer[0]
    context = {
        'manufacturer_name': dict_from_quiery_set['name'],
        'manufacturer_id': dict_from_quiery_set['id'],
        'edit': True,
    }
    if request.method == 'POST':
        if request.POST.get('manufacturer'):
            post = Manufacturer()
            post.name = request.POST.get('manufacturer')
            post.id = dict_from_quiery_set['id']
            post.save()
            return redirect(reverse_lazy('autos:manufacturers_page'))
        elif request.POST.get('cancel'):
            return redirect(reverse_lazy('autos:manufacturers_page'))
    else:
        return render(request, 'autos/add_or_edit_manufacturer.html', context)

"""


class UpdateMaker(LoginRequiredMixin, View):
    model = Manufacturer  # переменная для работы с таблицей 'Manufacturer' (models.py)
    template = 'autos/add_or_edit_manufacturer.html'
    success_url = reverse_lazy('autos:main_page')

    def get(self, request, pk):
        maker = get_object_or_404(self.model, pk=pk)  # аналог запроса Manufacturer.objects.filter(pk=pk).values()
        form = MakerForm(instance=maker)  # объект с html-шаблоном на основе запроса выше
        context = {'form': form}
        return render(request, self.template, context)

    def post(self, request, pk):
        maker = get_object_or_404(self.model, pk=pk) # для случая с неправильными данными в форме
        form = MakerForm(request.POST, instance=maker)
        if form.is_valid():
            form.save()
            return redirect(self.success_url)
        else:
            context = {'form': form}
            return render(request, self.template, context)


"""
def manufacturer_delete_form(request, pk):
    manufacturer = Manufacturer.objects.filter(pk=pk).values()
    context = {'manufacturer': manufacturer[0]}
    if request.method == 'POST':
        if request.POST.get('delete'):
            Manufacturer.objects.filter(pk=pk).delete()
            return redirect(reverse_lazy('autos:manufacturers_page'))
        elif request.POST.get('cancel'):
            return redirect(reverse_lazy('autos:manufacturers_page'))
    else:
        return render(request, 'autos/delete_manufacturer.html', context)
"""


class DeleteMaker(LoginRequiredMixin, View):
    model = Manufacturer
    template = 'autos/delete_manufacturer.html'
    success_url = reverse_lazy('autos:main_page')

    def get(self, request, pk):
        maker = get_object_or_404(self.model, pk=pk)
        context = {'maker': maker}
        return render(request, self.template, context)

    def post(self, request, pk):
        maker = get_object_or_404(self.model, pk=pk)
        maker.delete()
        return redirect(self.success_url)


"""
def auto_add_form(request):
    manufacturers = Manufacturer.objects.all()
    context = {'manufacturers': manufacturers}
    if request.method == 'POST':
        if request.POST.get('nickname') and request.POST.get('mileage') and request.POST.get('comment') and (request.POST.get('manufacturer') != '-----'):
            post = Auto()
            post.nickname = request.POST.get('nickname')
            post.mileage = request.POST.get('mileage')
            post.comments = request.POST.get('comment')
            '''
            Достаем id значения в поле <select>: Manufacturer.objects.filter(name=request.POST.get('manufacturer')).values()[0]['id'],
            где request.POST.get('manufacturer') - выбранное значение поля <select>,
            Manufacturer.objects.filter(фильтр).values() - запрос всех значений из таблицы Manufacturers, ответ - объект QuierySet[{}]
            [0]['id'] для <QuerySet [{'id': 1, 'name': 'BMW'}]> вернет 1
            '''
            manufacturer_id = Manufacturer.objects.filter(name=request.POST.get('manufacturer')).values()[0]['id']
            post.auto_id = manufacturer_id
            post.save()
            return redirect(reverse_lazy('autos:main_page'))
        # else - нет проверки введенных данных
        elif request.POST.get('cancel'):
            return redirect(reverse_lazy('autos:main_page'))
    elif request.method == 'GET':
        return render(request, 'autos/add_or_edit_auto.html', context)
"""


class CreateAuto(LoginRequiredMixin, View):
    template = 'autos/add_or_edit_auto.html'
    success_url = reverse_lazy('autos:main_page')

    def get(self, request):
        form = AutoForm()
        context = {'form': form}
        return render(request, self.template, context)

    def post(self, request):
        form = AutoForm(request.POST)
        context = {'form': form}
        if form.is_valid():
            form.save()
            return redirect(self.success_url)
        else:
            context = {'form': form}
            return render(request, self.template, context)


"""
def auto_edit_form(request, pk):
    auto = Auto.objects.filter(pk=pk).values()
    chosen_man = Manufacturer.objects.filter(pk=auto[0]['auto_id']).values()
    manufacturers = Manufacturer.objects.all()
    context = {
        'auto': auto[0],
        'manufacturers': manufacturers,
        'chosen_man': chosen_man[0],
        'edit': True,
    }
    if request.method == 'POST':
        if request.POST.get('nickname') and request.POST.get('mileage') and request.POST.get('comment') and (request.POST.get('manufacturer') != '-----'):
            post = Auto()
            post.nickname = request.POST.get('nickname')
            post.mileage = request.POST.get('mileage')
            post.comments = request.POST.get('comment')
            '''
            Достаем id значения в поле <select>: Manufacturer.objects.filter(name=request.POST.get('manufacturer')).values()[0]['id'],
            где request.POST.get('manufacturer') - выбранное значение поля <select>,
            Manufacturer.objects.filter(фильтр).values() - запрос всех значений из таблицы Manufacturers, ответ - объект QuierySet[{}]
            [0]['id'] для <QuerySet [{'id': 1, 'name': 'BMW'}]> вернет 1
            '''
            manufacturer_id = Manufacturer.objects.filter(name=request.POST.get('manufacturer')).values()[0]['id']
            post.auto_id = manufacturer_id
            post.save()
        elif request.POST.get('cancel'):
            return redirect(reverse_lazy('autos:main_page'))
    elif request.method == 'GET':
        return render(request, 'autos/add_or_edit_auto.html', context)
"""


class UpdateAuto(LoginRequiredMixin, View):
    model = Auto
    template = 'autos/add_or_edit_auto.html'
    success_url = reverse_lazy('autos:main_page')

    def get(self, request, pk):
        auto = get_object_or_404(self.model, pk=pk)
        form = AutoForm(instance=auto)
        context = {'form': form}
        return render(request, self.template, context)

    def post(self, request, pk):
        auto = get_object_or_404(self.model, pk=pk)
        form = AutoForm(request.POST, instance=auto)
        if form.is_valid():
            form.save()

first_django_project/autos/templates/autos/add_manufacturer.html
{% extends 'home/base_bootstrap.html' %}
{% block content %}
<br>
<form name="manufacturer" method="post">
    {% csrf_token %}
    <p><input placeholder="Производитель" type="text" name="manufacturer"></p>
    <p>
        <input type="submit" value="Добавить">
        <input type="submit" value="Отмена" name="cancel">
    </p>
{% endblock %}

first_django_project/autos/templates/autos/add_or_edit_auto.html
{% extends 'home/base_menu.html' %}
{% block content %}
<!--
<br>
{# Этот кусок для редактирования существующей в базе записи #}
{% if edit %}
<form name="auto" method="post">
    {% csrf_token %}
    <p><input placeholder="Nickname" type="text" name="nickname" value="{{auto.nickname}}"></p>
    <p><input placeholder="Mileage" type="int" name="mileage" value="{{auto.maleage}}"></p>
    <p><input placeholder="Comment" type="text" name="comment" value="{{auto.comments}}"></p>
    <p>
        <select name="manufacturer">
        {% if manufacturers %}
            {% for manufacturer in manufacturers %}
                <option value="{{manufacturer.name}}">{{manufacturer.name}}</option>
            {% endfor %}
        {% else %}
            <option value="-----">-----</option>
        {% endif %}
        <option selected="{{chosen_man.name}}">{{chosen_man.name}}</option>
        </select>
    </p>
    <p>
        <input type="submit" value="Обновить">
        <input type="submit" value="Отмена" name="cancel">
    </p>
</form>
{# Этот кусок для создания новой записи в базе #}
{% else %}
<form name="auto" method="post">
    {% csrf_token %}
    <p><input placeholder="Nickname" type="text" name="nickname"></p>
    <p><input placeholder="Mileage" type="int" name="mileage"></p>
    <p><input placeholder="Comment" type="text" name="comment"></p>
    <p>
        <select name="manufacturer">
        {% if manufacturers %}
            {% for manufacturer in manufacturers %}
                <option value="{{manufacturer.name}}">{{manufacturer.name}}</option>
            {% endfor %}
        {% else %}
            <option value="------">-----</option>
        {% endif %}
        </select>
    </p>
    <p>
        <input type="submit" value="Добавить">
        <input type="submit" value="Отмена" name="cancel">
    </p>
</form>
{% endif %}
-->
<form action="" method="post">
    {% csrf_token %}
    <br>
    <table>{{ form.as_table }}</table>
    <br>
    <input type="submit" value="Добавить">
    <input type="submit" onclick="window.location='{% url 'autos:main_page' %}'; return false;" value="Отмена">
</form>
{% endblock %}

first_django_project/autos/templates/autos/add_or_edit_manufacturer.html
{% extends 'home/base_menu.html' %}
{% block content %}
<!--
<br>
{% if edit %}
<form name="manufacturer" method="post">
    {% csrf_token %}
    <p><input placeholder="Производитель" type="text" name="manufacturer", value="{{manufacturer_name}}"></p>
    <p>
        <input type="submit" value="Обновить">
        <input type="submit" value="Отмена" name="cancel">
    </p>
{% else %}
<form name="manufacturer" method="post">
    {% csrf_token %}
    <p><input placeholder="Производитель" type="text" name="manufacturer"></p>
    <p>
        <input type="submit" value="Добавить">
        <input type="submit" value="Отмена" name="cancel">
    </p>
{% endif %}
-->

<form action="" method="post">
    {% csrf_token %}
    <br>
    <table> {{ form.as_table }} </table>
    <br>
    <input type="submit" value="Добавить">
    <input type="submit" onclick="window.location='{% url 'autos:main_page' %}'; return false;" value="Отмена">
</form>
{% endblock %}

first_django_project/autos/templates/autos/delete_auto.html
{% extends 'home/base_menu.html' %}
{% block content %}
<!--
<h1>Удаление автомобиля</h1>
<p>Вы собираетесь удалить автомобиль "{{auto.nickname}}"</p>
<p>
<form name="auto" method="post">
   {% csrf_token %}
    <input type="submit" value="Удалить" name="delete">
    <input type="submit" value="Отмена" name="cancel">
</form>
</p>
-->
<h1>Удаление автомобиля</h1>
<p>Вы собираетесь удалить автомобиль "{{auto.nickname}}"</p>
<p>
<form action="" method="POST">
   {% csrf_token %}
   <input type="submit" value="Удалить">
   <input type="submit" onclick="window.location='{% url 'autos:main_page' %}'; return false;" value="Отмена">
</form>
</p>
{% endblock %}

first_django_project/autos/templates/autos/delete_manufacturer.html
{% extends 'home/base_menu.html' %}
{% block content %}
<!--
<h1>Удаление производителя</h1>
<p>Вы собираетесь удалить бракодела "{{manufacturer.name}}"</p>
<p>
<form name="manufacturer" method="post">
   {% csrf_token %}
    <input type="submit" value="Удалить" name="delete">
    <input type="submit" value="Отмена" name="cancel">
</form>
</p>
-->
<h1>Удаление производителя</h1>
<p>Вы собираетесь удалить бракодела "{{maker.name}}"</p>
<p><form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Удалить">
  <input type="submit" onclick="window.location='{% url 'autos:main_page' %}'; return false;" value="Отмена">
</form></p>
{% endblock %}

first_django_project/autos/templates/autos/delete_record.html
{% extends 'home/base_bootstrap.html' %}
{% block content %}
<h1>Удаление автомобиля</h1>
<p>Вы собираетесь удалить автомобиль "{{auto.nickname}}"</p>
<p>
<form name="auto" method="post">
   {% csrf_token %}
    <input type="submit" value="Удалить" name="delete">
    <input type="submit" value="Отмена" name="cancel">
</form>
</p>
{% endblock %}

first_django_project/autos/templates/autos/main_page.html
{% extends 'home/base_menu.html' %}
{% block content %}
<h1>Список автомобилей</h1>
{% if autos %}
    <ul>
        {% for auto in autos %}
        <li>{{auto.nickname}} ({{auto.auto}}) (<a href="{% url 'autos:edit_auto' auto.id %}">Обновить</a> | <a href="{%  url 'autos:delete_auto' auto.id %}">Удалить</a>)</li>
        {% endfor %}
    </ul>
{% else %}
    <p>В базе нет записей</p>
{% endif %}
<p>
<a href="{% url 'autos:add_auto' %}">Добавить ведро</a>
</p>
<p>
<a href="{% url 'autos:makers_page' %}">Просмотр бракоделов</a> ({{ counter }}) | <a href="{% url 'autos:add_maker' %}">Добавить бракодела</a>
</p>
{% endblock %}

first_django_project/autos/templates/autos/manufacturers_page.html
{% extends 'home/base_menu.html' %}
{% block content %}
<h1>Список бракоделов</h1>
{% if makers %}
    <ul>
        {% for maker in makers %}
        <li>{{maker.name}} (<a href="{% url 'autos:edit_maker' maker.id %}">Обновить</a> | <a href="{% url 'autos:delete_maker' maker.id %}">Удалить</a>)</li>
        {% endfor %}
    </ul>
{% else %}
    <p>В базе нет записей</p>
{% endif %}
<p>
<a href="{% url 'autos:add_maker' %}">Добавить бракодела</a>
</p>
<p>
<a href="{% url 'autos:main_page' %}">Назад к списку машин</a>
</p>
{% endblock %}